import Vue from 'vue';
import {
  Affix,
  Anchor,
  AutoComplete,
  Alert,
  Avatar,
  BackTop,
  Badge,
  Breadcrumb,
  Button,
  Calendar,
  Card,
  Collapse,
  Carousel,
  Cascader,
  Checkbox,
  Col,
  DatePicker,
  Divider,
  Dropdown,
  Form,
  Icon,
  Input,
  InputNumber,
  Layout,
  List,
  LocaleProvider,
  message,
  Menu,
  Modal,
  notification,
  Pagination,
  Popconfirm,
  Popover,
  Progress,
  Radio,
  Rate,
  Row,
  Select,
  Slider,
  Spin,
  Steps,
  Switch,
  Table,
  Transfer,
  Tree,
  TreeSelect,
  Tabs,
  Tag,
  TimePicker,
  Timeline,
  Tooltip,
  // Mention,
  Upload,
  // version,
  Drawer,
  Skeleton,
  Comment,
  ConfigProvider,
  Base,
} from 'ant-design-vue';


export default {
  components:{
    [Affix.name]: Affix,
[Anchor.name]: Anchor,
[Anchor.Link.name]: Anchor.Link,
[AutoComplete.name]: AutoComplete,
[AutoComplete.Option.name]: AutoComplete.Option,
[AutoComplete.OptGroup.name]: AutoComplete.OptGroup,
[Alert.name]: Alert,
[Avatar.name]: Avatar,
[BackTop.name]: BackTop,
[Badge.name]: Badge,
[Breadcrumb.name]: Breadcrumb,
[Breadcrumb.Item.name]: Breadcrumb.Item,
[Button.name]: Button,
[Button.Group.name]: Button.Group,

[Calendar.name]: Calendar,
[Card.name]: Card,
[Card.Meta.name]: Card.Meta,
[Card.Grid.name]: Card.Grid,
[Collapse.name]: Collapse,
[Collapse.Panel.name]: Collapse.Panel,
[Carousel.name]: Carousel,
[Cascader.name]: Cascader,
[Checkbox.name]: Checkbox,
[Checkbox.Group.name]: Checkbox.Group,
[Col.name]: Col,
[DatePicker.name]: DatePicker,
[DatePicker.MonthPicker.name]: DatePicker.MonthPicker,
[DatePicker.RangePicker.name]: DatePicker.RangePicker,
[DatePicker.WeekPicker.name]: DatePicker.WeekPicker,
[Divider.name]: Divider,
[Drawer.name]: Drawer,
[Dropdown.name]: Dropdown,
[Dropdown.Button.name]: Dropdown.Button,
[Form.name]: Form,
[Form.Item.name]: Form.Item,
[Icon.name]: Icon,
[Input.name]: Input,
[Input.Group.name]: Input.Group,
[Input.Search.name]: Input.Search,
[Input.TextArea.name]: Input.TextArea,
[InputNumber.name]: InputNumber,
[Layout.name]: Layout,
[Layout.Header.name]: Layout.Header,
[Layout.Footer.name]: Layout.Footer,
[Layout.Sider.name]: Layout.Sider,
[Layout.Content.name]: Layout.Content,
[List.name]: List,
[List.Item.name]: List.Item,
[List.Item.Meta.name]: List.Item.Meta,
[LocaleProvider.name]: LocaleProvider,
[Menu.name]: Menu,
[Menu.Item.name]: Menu.Item,
[Menu.SubMenu.name]: Menu.SubMenu,
[Menu.Divider.name]: Menu.Divider,
[Menu.ItemGroup.name]: Menu.ItemGroup,
[Modal.name]: Modal,
[Pagination.name]: Pagination,
[Popconfirm.name]: Popconfirm,
[Popover.name]: Popover,
[Progress.name]: Progress,
[Radio.name]: Radio,
[Radio.Group.name]: Radio.Group,
[Radio.Button.name]: Radio.Button,
[Rate.name]: Rate,
[Row.name]: Row,
[Select.name]: Select,
[Select.Option.name]: Select.Option,
[Select.OptGroup.name]: Select.OptGroup,
[Slider.name]: Slider,
[Spin.name]: Spin,
[Steps.name]: Steps,
[Steps.Step.name]: Steps.Step,
[Switch.name]: Switch,
[Table.name]: Table,
[Table.Column.name]: Table.Column,
[Table.ColumnGroup.name]: Table.ColumnGroup,
[Tree.name]: Tree,
[Tree.TreeNode.name]: Tree.TreeNode,
[TreeSelect.name]: TreeSelect,
[TreeSelect.TreeNode.name]: TreeSelect.TreeNode,
[Tabs.name]: Tabs,
[Tabs.TabPane.name]: Tabs.TabPane,
[Tabs.TabContent.name]: Tabs.TabContent,
[Tag.name]: Tag,
[Tag.CheckableTag.name]: Tag.CheckableTag,
[TimePicker.name]: TimePicker,
[Timeline.name]: Timeline,
[Timeline.Item.name]: Timeline.Item,
[Tooltip.name]:Tooltip,
[Upload.name]:Upload,
[Upload.Dragger.name]: Upload.Dragger

  }
}
